# Generated by Django 4.2.6 on 2026-03-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serial_comm", "0007_averages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_id",
                    models.CharField(default="RS485-PROD-01", max_length=100),
                ),
                (
                    "station_name",
                    models.CharField(default="Default Station", max_length=255),
                ),
            ],
        ),
    ]
